### ISSUE TITLE
lfw accuracy

### ISSUE THREAD

**Issue by ghost** [inlmouse/MS-Celeb-1M_WashList#1]
thank for your sharing, can you release lfw accuracy with your wahlist and wuxiang's washlist?

**Comment by inlmouse** [comment]
As I described in ReadMe, there're over 1000 overlap identities between MS-Celeb-1M and LFW. So we believed that the LFW accuracy can not explain any problem before those overlap identities were removed from the list. The CNN we used to extract feature was trained on CASIA-WebFace.
