### ISSUE TITLE
what is the code in msceleb1m_lfw_overlaplist.txt

### ISSUE THREAD

**Issue by Alireza-Akhavan** [inlmouse/MS-Celeb-1M_WashList#2]
Would you mind telling me about the IDs in the file "1m_lfw_overlaplist.txt" ?
Ms-Celeb-1M IDs are unique id like 'm.03t4cz' or search name like 'Aaron Eckhart'. LFW IDs are names.
I can't understand what are codes in the msceleb1m_lfw_overlaplist.txt file?

**Comment by inlmouse** [comment]
Sorry about the unclear description in README. The Ms-Celeb-1M was rearranged by the washlist in a zero-indexed label. Just like this: '0/m.0109kg_14-FaceId-0.jpg'. All the images with the same label will be regard as one individual person. These labels are also the IDs in the overlaplist.

**Comment by inlmouse** [comment]
You could reopen the issue or start a new one, if you have any further questions regarding this topic.
