### ISSUE TITLE
The CNN model used to extract the features?

### ISSUE THREAD

**Issue by Julyustc** [inlmouse/MS-Celeb-1M_WashList#4]
would you mind share the CNN model that used to extract features? i want to clean the vgg-face2 dataset. 
thank u.

**Comment by inlmouse** [comment]
@Julyustc Sorry, this work was done in the previous company I worked for. I cannot share the CNN model without my former employer's authorization. Now, I have left and unemployed :( . As for vgg-face2 dataset, I think you should refer [this repo](https://github.com/happynear/FaceDatasets).
